import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";


const font = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} ${font.className} antialiased`}
      >
        <div className="max-w-[1920px] mx-auto text-white">
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
